### ISSUE TITLE
support for name="fieldName[]"

### ISSUE THREAD

**Issue by th3fallen** [formsy/formsy-react#102]
Currently it doesnt seem doing fields named the same thing with [] works is that intended? and is there a way to work around it?

**Comment by twisty** [comment]
Note: the square-bracket convention is common and comes from php, but it isn't necessary for getting a multi-value data structure [according to the html5 spec](https://www.w3.org/TR/html5/sec-forms.html#sec-constructing-the-form-data-set). i.e. In `html5` a bunch of inputs with the same name should return a data-set, regardless of the square-bracket convention.

That said, you could maybe work around this using a naming convention that includes keys in your `name` prop, and use [mapping](https://github.com/formsy/formsy-react/blob/master/API.md#mapping) to munge your form data on submit.

**Comment by MilosRasic** [comment]
I think the usual "react way" would be to have your list of fields representing an array of values in a single component which acts as a field itself, with the array as a value, just like checkbox group from formsy-react-components: https://github.com/twisty/formsy-react-components/blob/master/src/components/checkbox-group.js
