### ISSUE TITLE
Can we use this library for Materialize css 

### ISSUE THREAD

**Issue by Chandrika-Desai** [formsy/formsy-react#104]
Hi, we are using the combination of React + Materialize css (https://materializecss.com/), so was going through the possible validation library that I can use. So just wanted to check with you guys can I use this for materialize css framework

**Comment by MilosRasic** [comment]
Sorry for the late response. formsy is a react library. It can consume any React component as a form field as long as you write a wrapper HOC. https://react-materialize.github.io/#/ looks like it would do the trick, although I'm not sure depending on a library that depends on both React and jQuery in 2018 is a good idea. material-ui looks like a good alternative if all you want is material design.

It's also a good opportunity to open source your formsy wrapper for your favorite form field library :)
