### ISSUE TITLE
onChange not working with Formsy

### ISSUE THREAD

**Issue by ihd2911** [formsy/formsy-react#109]
Following is my code, in this handleChange is not working.
I need to get value on change to get cities.

```
<SelectFormsy
className="mb-16"
name="state"
label="state"
value={state}
onChange={this.handleChange}
>
          {stateReducer.state.map((s, idx) => (
                 <MenuItem key={idx} value={s.stateName}>{s.stateName}</MenuItem>
           ))}
</SelectFormsy>
```
Constructor
this.handleChange= this.handleChange.bind(this);

Function

```
 handleChange= (event) => {
        console.log(['state',event.target]);
        this.setState({stateId:event.target.value});
    }
```

**Comment by rkuykendall** [comment]
Formsy doesn't supply a `SelectFormsy` component, and I don't see Formsy used in any of this code aside from that component name. If your handle change function isn't being called, or isn't working in some other way, we would need to see how it's related to this library.

**Comment by kenkopelson** [comment]
Should the value on the control be value={state.stateId} and not just "state"?  How is the select control supposed to know what field out of the 'state' object to compare against?

Typically, on these types of controls, the value needs to match the thing that is changed in the onChange call:

```
state = {
  someValue: ''
}

<SelectFormy value={this.state.someValue} onChange={(event) => this.setState({someValue:event.target.value})/>

```
