### ISSUE TITLE
Modernizing the tests

### ISSUE THREAD

**Issue by MilosRasic** [formsy/formsy-react#115]
nodeunit is depracated, as detailed in the library's readme https://github.com/caolan/nodeunit

It's a big wtf moment for anyone wanting to contribute who is used to Mocha or Jest. Contributors with no experience would be learning something they would be unlikely to use in another project.

I'm thinking either Mocha/Sinon/Chai combo or Jest, both with Enzyme. Jest is the more popular option, but if we use the other stack we wouldn't have to rewrite the Sinon spies which are already used by current Formsy tests. I also prefer Chai's assertion format personally.

Anyone else have any opinions?

**Comment by rkuykendall** [comment]
I think Jest is the clear winner here, as far as the standards. The upgrade should be relatively easy. I think I'll make this my next task once most merges are done.
