### ISSUE TITLE
Where is the changelog ?

### ISSUE THREAD

**Issue by Fandekasp** [formsy/formsy-react#118]
formsy-react got an npm release v1.1.5 regarding this change: https://github.com/formsy/formsy-react/compare/v1.1.4...32843279adbaa64248709e3a2b208e54ad2ab0c6

But I do not see any new git tag, no addition in the [changelog](https://github.com/formsy/formsy-react/blob/master/CHANGELOG.md) or in the [github releases](https://github.com/formsy/formsy-react/releases)

Can you update the release notes and tell me which one I should be regularly looking at (changelog or github releases) ? Thank you

**Comment by Fandekasp** [comment]
ping @MilosRasic  @twisty @rkuykendall

**Comment by MilosRasic** [comment]
My sincerest apologies. It looks like all of us have been pretty busy lately. I published the 1.1.5 in a hurry and forgot to update the changelog. Should be publishing 1.1.6 soon.

As for the source of truth, I'm annoyed that there's two, but this is how we inherited the project and there were and still are more important issues to address. Suggestion on which one we should keep maintaining are welcome.

**Comment by Fandekasp** [comment]
Thanks for the reply. Since renovate auto parses GitHub releases, I'd rather have this, but this makes for a poor reason. I'm fine with any location as long as you follow semantic releases :)

**Comment by twisty** [comment]
It was a slip-up not to tag the release. Our bad. 😿

I guess the minimum going forward is make sure to `git tag` before publish? We could probably add a safeguard for this in a npm lifecyle script but, for now, lets try not to get hung up on this and keep on rocking.

**Comment by MilosRasic** [comment]
`npm version` will commit and tag by default

**Comment by rkuykendall** [comment]
`npm run deploy` will update the changelog, and tag, and we will no longer have to remember. I've also added information the the README about our PR title format which builds the changelog, and added information in the PR template about complying with the guidelines. Thank you for bringing this to our attention.
