### ISSUE TITLE
Formsy cannot access the actual input refs. This prevents autofocusing to an invalid field with HTML5 form validation turned off

### ISSUE THREAD

**Issue by TheMcMurder** [formsy/formsy-react#121]
Currently because the `withFormly` HOC doesn't store references to the actual input fields. It's impossible for the top level form to access the actual references to the HTML inputs, unless you reimplement ref registration inside your own component. 

This is a problem because if you want to focus (with `noValidate={true}`) to an invalid field on invalid submit with you cannot access the html nodes to call `.focus()`.

If the HOC withFormly provided a function to store a HTML node (ref) inside itself then the form would have access to everything it needed.

PR coming soon.

**Comment by MilosRasic** [comment]
I'm struggling to see how this cannot be achieved with the existing `innerRef` prop. It's different of course: you'd store the props in the Formsy form's parent component and handle calling focus from there.

Is there a limitation of `innerRef` I'm failing to see?

**Comment by TheMcMurder** [comment]
There are two potential issues with innerRef for my use case, one is a management problem and the other is a data problem.

1) I have to store all refs that I might focus on at the top level, this means formsy and I are both storing an array of refs at the top level. I'm storing refs to a html nodes and formsy to the components. It works of course but it's a lot of extra code/management.
2) AFAIK there is no dynamic way to figure out which html ref maps to which invalid field except using the index or repeating the name issue

Assuming I store the html refs at the top level my psuedocode looks something like this:
```jsx
// MyComponent
// stores refs to all Input Children html nodes
//...
render () {
  return (
  <Form onInvalidSubmit={this.focusOnFirstInvalid}>
  // form stores refs to all Inputs
    <InputDecoratedComp name='foo'>
    </InputDecoratedComp>
    <InputDecoratedComp name='bar'>
    </InputDecoratedComp>
  </Form>
  )
}

focusOnFirstInvalid = () => {
  // figure out the invalid field
  // using the invalid fields index focus on the matching index of refs and hope that the two arrays are in perfect sync or duplicate the name logic formsy is already using.
}
```

Fundamentally I believe this problem can be solved by the existing library, but it requires a lot of custom code and work at the implementation level. PR #125 add's a few lines of code (less than 5 lines of source code, ignoring tests) and makes it much easier to access the html nodes without storing them yourself at the top level, but it's also opt-in so those extra lines of code shouldn't affect people who don't need them.

**Comment by rkuykendall** [comment]
Closing this issue as described in #125
