### ISSUE TITLE
Issues in `/lib` in release v2.0

### ISSUE THREAD

**Issue by alanyinjs** [formsy/formsy-react#130]
I realised that the some of the source code in the transpiled directory `/lib` were updated before release v2.0. I believe the change could potentially cause the `props` passed in by the formsy HOC impossible to override:
![capture](https://user-images.githubusercontent.com/25688258/50749637-40046380-1294-11e9-8f63-09138785d847.PNG)

With HOCs, we have to be careful with the order of the props being passed in. `{...this.props}` has to be after the default HOC props. Otherwise those props defined in the HOC cannot be overridden. This is still correctly implemented in the source code in `/src` in release v2.0(as we can see that ...this.props is the last one to be merged into `propsForElement`):
![capture2](https://user-images.githubusercontent.com/25688258/50749679-907bc100-1294-11e9-8e2a-b0708d02f502.PNG)

Not sure why the source code in `/src` remains unchanged and correct but the source code in `/lib` changed the order of how `...this.props` gets merged in the props of the returned component?

**Comment by rkuykendall** [comment]
@alanyinjs Thank you for this issue. It looks like this issue has been fixed?

![image](https://user-images.githubusercontent.com/796717/58421856-14292500-805f-11e9-84a3-b6c9f2b99e15.png)
