### ISSUE TITLE
conflict in value property while using Material-ui checkbox

### ISSUE THREAD

**Issue by oladhari** [formsy/formsy-react#131]
Thanks for maintaining this library

We have a component using a [Material-ui Checkbox](https://material-ui.com/api/checkbox/) that is decorated with `withFormsy`.
and it raised this error when trying to check it: 
![screenshot from 2019-01-16 12-21-51](https://user-images.githubusercontent.com/13581057/51238116-7723f480-19b9-11e9-97a7-d07c5a04d579.png)

To fix the problem we needed to set a `static defaultValue` property to our decorated component because the Material-ui's Checkbox is using the same property **value** as `@withFormsy` and it should be a string, yet Formsy seems to expect a default value to be considered a controlled input.

Is there a better way to solve this issue ? This conflict of properties between libs is a bit vexing, would be great if Formsy could handle this.

Thank you
```JS
@withFormsy
export default class Checkbox extends Component {
 
  static defaultValue = ""; // Fix for Formsy

  handleChange = event => {
    const {setValue} = this.props;
    setValue(event.target.checked);
  };

  render() {
    const {getValue} = this.props;

    return (
      <MuiCheckbox
        className="className"
        name="name"
        onChange={this.handleChange}
        checked={value}
        data-checked={value}
        value={String(value)} // Fix for MUI
      />
    );
  }
}


```

**Comment by ThibautMarechal** [comment]
PS: You don't use your props.getValue(). (I'm sure it's a copy paste error ;) )

This is not an issue. If you dont have a value when mounting your component (getValue() will return undefined). 
React don't like to witch from uncontrolled component to controlled component. (Your error in the console)
The way you handle that is the good one, to defined a static property "defaultValue". (https://github.com/formsy/formsy-react/blob/1c5cc126f6009167871d9ed3627d9d13a51dd792/src/Wrapper.js#L224)

This nice feature should be added in the documentation, i didn't know until now.

**Comment by oladhari** [comment]
@ThibautMarechal Thank you very much for your reply and help
