### ISSUE TITLE
Any react-native support?

### ISSUE THREAD

**Issue by LeoIannacone** [formsy/formsy-react#133]
It would be nice if it could work with react-native

**Comment by track0x1** [comment]
Hi @LeoIannacone 
Feel free to check out https://github.com/track0x1/formsy-react-native

**Comment by Azerothian** [comment]
track0x1 fork is a little too old, throws errors on deprecated content

for ref of a more recent fork as on 2.2.1

npm: @vostro/formsy-react-native

https://github.com/VostroNet/formsy-react-native

**Comment by rkuykendall** [comment]
This is really cool. Is that final commit all it took to make it work? If this is something people are interested in, we could make sure to keep it up to date.
