### ISSUE TITLE
Why there is no removeValidationRule?

### ISSUE THREAD

**Issue by mgustus** [formsy/formsy-react#141]
Hi,

After adding a custom validation rule with `addValidationRule` in `componentDidMount()`, I think it is reasonable to remove it in `componentWillUnmount()`. It looks like there could be a memory leak because the custom rule function stays in the `validationRules` collection with all its closures.
Why there is no `removeValidationRule`?

Thanks.

**Comment by rkuykendall** [comment]
I always found `addValidationRule` globally once to add rules. In your use case, should you be including the validator inline, like this?

https://github.com/formsy/formsy-react/blob/master/API.md#validations

**Comment by mgustus** [comment]
Yes, using an inline validator solves this problem.
Thank you 👍

**Comment by rkuykendall** [comment]
Thank you for responding!
