### ISSUE TITLE
mixing costum and predefined validation rules 

### ISSUE THREAD

**Issue by meneman** [formsy/formsy-react#143]
Hi, 
Is it possible to combine costum rules and preexisting formsy validation rules on the same input? like in this example from the documentation:

```
<MyInputComponent name="number" validations={{
  isNumeric: true,
  isLength: 5
}}/>
<MyInputComponent name="number" validations={{
  myCustomIsFiveValidation: function (values, value) {
    values; // Other current values in form {foo: 'bar', 'number': 5}
    value; // 5
    return 5 === value ? true : 'No five'; // You can return an error
  }
}}/>
```

Is it possible to have the isNumeric and isLength basic validation rules together with the myCustomIsFiveValidation on the same input?

**Comment by rkuykendall** [comment]
I don't see any place we do this in the test but my guess is yes. Have you tried it? Or is this a feature request?
