### ISSUE TITLE
Question: passing value from one input to another component in the form

### ISSUE THREAD

**Issue by axelfriberg** [formsy/formsy-react#145]
I would like to pass the value of one formsy input component to another component in my Form. So let's say something like this: 
```javascript
<Formsy ref={this.form}>
  <FormsyInput name="input"></FormsyInput>
  <AnotherComponent data={this.form.getModel().input}>
</Formsy>
```
But I  can't seem to get this to work properly since I'm trying to acess the ref to the form while it is being created. So what I have now is instead: 
```javascript
<Formsy onChange={currentValues => this.setState({input: currentValue.input})>
  <FormsyInput name="input"></FormsyInput>
  <AnotherComponent data={this.state.input}>
</Formsy>
```

What I don't like about this approach is that I'm keeping my own copy of the state that Formsy already has. So what would you say is the best approach to passing values from a Formsy input?

**Comment by rkuykendall** [comment]
I would actually do it exactly like you're doing it now. Personally, I always build a 'FormManager' class anyways for doing little helper methods like `isSubmitDisabled`. On second thought, those utilities might actually be great Formsy features...

But back to your issue, if keeping a state of the form bothers you, why not pass the form ref down to your component and allowing it to call getModel() itself when it needs it? It would only have to check that the ref is not undefined for it's first render.

**Comment by axelfriberg** [comment]
Okey, yeah I can give that a go as well. Now I at least know some options. Thanks!
