### ISSUE TITLE
Reset form does not work on field name with dot notation

### ISSUE THREAD

**Issue by jacklimwenjie** [formsy/formsy-react#179]
Field with `name` of `foo.bar`, when submit will result in an object of `{ foo: { bar: value } }`. 

However, when reset the form with the same object `{ foo: { bar: value } }`, the field with `name` of `foo.bar` does not get the value. Resetting with a flatten object e.g. `{ "foo.bar": value } }` does the trick but it would be better if Formsy supports nested object out of the box since dot notation is supported on the field `name`.

**Comment by rkuykendall** [comment]
This is a great issue, thank you!

**Comment by rkuykendall** [comment]
Released:

# v2.0.1
- Respect dot notation in reset (#393)  a2d2e5f
- Remove unnecesary externalError state (#398)  d4eb73e
- Allow validation errors to be React elements (#394)  4096296
- Update rollup plugin libraries (#397)  bebefbe
- Improvements to README and PR Template (#395)  df5af84
- Fix types in Formsy spec tests (#396)  954370a
- Remove unused Formsy props; tighten types; improve runRules (#392)  0eaeef7
- Rename cloneIfObject to protectAgainstParamReassignment; Fix isObject (#391)  49fc634
- Added possibility to use browser builtin submit (#226)  761b3ef
- Improve test coverage (#378)  b8881d0
- Dependabot Automatic Library Bumps (#376)  8b5a0db
- Use React's New Context API (#198)  a79eec2
- Fix in-page link to updateInputsWithValue  6fcc682
- Change coveralls from dependency to dev dependency  c9d9db5
- Add coverage to gitignore  0afef60

https://github.com/formsy/formsy-react/compare/v2.0.0...v2.0.1
