### ISSUE TITLE
Feature request : nested form

### ISSUE THREAD

**Issue by ThibautMarechal** [formsy/formsy-react#186]
"form" element cannot be nested.
My need is to have multiple forms with its own validation inside the main form

Example of a model : 
```
{
  house : {
    name : "name"
    description : "description"
    levels : [
      {
        name : "name",
      }
    ] 
  }
}
```
In this case i want a general form to edit a house.
And for the field "levels" i want multiple form for each level.

For the moment, I have a hack when i extend Formsy and override the render to render a "div" element  instead of a "form" element.

It would be nice to a have an additional props that can override the "form" element to another one.

I can make a pull request if you think it's a good idea to put in Formsy.

**Comment by rmaroun** [comment]
Definitely something needed to be able to manage complex forms with multiple levels as for now Formsy only can do one level form (simple forms).

**Comment by rkuykendall** [comment]
Is this something that can just be solved with our dot notation support? If not, why?

**Comment by rmaroun** [comment]
@rkuykendall how would you do it?

**Comment by rkuykendall** [comment]
@rmaroun Rough mock of course but this was what I was suggesting / asking if it would solve the issue:

```ts
<Formsy>
  <FormsyInput name='house.name' />
  <FormsyInput name='house.description' />
  {range(this.numLevels).forEach(numLevel => ({
    <FormsyInput name={`house.levels[${numLevel}].name`} />
  }))}
  <a onClick={() => this.numLevels++}>Add Level</a>
</Formsy>
```

**Comment by rkuykendall** [comment]
For the future record, this was closed because you can now specify the form element that formsy uses!
