### ISSUE TITLE
Feature Request : Use the new Context API

### ISSUE THREAD

**Issue by ThibautMarechal** [formsy/formsy-react#194]
For now Formsy use the legacy context api. (https://reactjs.org/docs/legacy-context.html)
We should use the new context api. (https://reactjs.org/docs/context.html)
So we don't have warnings when running in strict-mode.

**Comment by rkuykendall** [comment]
This is now our #1 most :+1:'d issue!

For those who find this issue, @ThibautMarechal is working on a PR here: https://github.com/formsy/formsy-react/pull/198

**Comment by ThibautMarechal** [comment]
@rkuykendall I have just an issue, If we use the new context api, it means that Formsy must be a PeerDependencies.
If a another library share Formsy components, it must have the same context. Right ?

**Comment by rkuykendall** [comment]
I will not lie and say I understand this issue very well. I did have a similar problem with another library, where moving a shared dependency to peer fixed a shared state issue, but that seems like a concern for other libraries? It seems reasonable to me to have to install another library that adds components alongside formsy and not instead of formsy.

**Comment by ThibautMarechal** [comment]
https://github.com/formsy/formsy-react/pull/198

**Comment by rkuykendall** [comment]
Thanks for closing! This will be released with Formsy 2.0.1 either today or tomorrow morning :)

**Comment by rkuykendall** [comment]
Released:

# v2.0.1
- Respect dot notation in reset (#393)  a2d2e5f
- Remove unnecesary externalError state (#398)  d4eb73e
- Allow validation errors to be React elements (#394)  4096296
- Update rollup plugin libraries (#397)  bebefbe
- Improvements to README and PR Template (#395)  df5af84
- Fix types in Formsy spec tests (#396)  954370a
- Remove unused Formsy props; tighten types; improve runRules (#392)  0eaeef7
- Rename cloneIfObject to protectAgainstParamReassignment; Fix isObject (#391)  49fc634
- Added possibility to use browser builtin submit (#226)  761b3ef
- Improve test coverage (#378)  b8881d0
- Dependabot Automatic Library Bumps (#376)  8b5a0db
- Use React's New Context API (#198)  a79eec2
- Fix in-page link to updateInputsWithValue  6fcc682
- Change coveralls from dependency to dev dependency  c9d9db5
- Add coverage to gitignore  0afef60

https://github.com/formsy/formsy-react/compare/v2.0.0...v2.0.1
