### ISSUE TITLE
Deprecation of React.createClass

### ISSUE THREAD

**Issue by rkuykendall** [formsy/formsy-react#2]
Original issue: https://github.com/christianalfoni/formsy-react/issues/437

> Hi, after upgrading React I get this warning:

> ```Warning: Formsy: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.```

**Comment by rkuykendall** [comment]
I believe this was fixed by the 1.0 beta merge, and we can close this issue after we cut the next release.

**Comment by apuntovanini** [comment]
It is fixed in 1.0 beta merge

**Comment by MilosRasic** [comment]
Latest release is fully migrated to classy components and tested in a real project. Closing this.
