### ISSUE TITLE
Validation error for custom validation is not working

### ISSUE THREAD

**Issue by vikasrohit** [formsy/formsy-react#21]
I have a custom validation for my formsy implementation and I am using HOC to convert my custom components to be formsy components. Now the problem is that when I try to specify the validation error for the custom validation via `validationErrors` property, `getErrorMessage()` call does not return the validation message. It works if I add `validationError` though.

Is it something which is wrong with my configuration/code or a known bug?

**Update:** CodePen for reproducing the problem. https://codepen.io/vikasrohit/pen/yPPPqj Please note that it is not showing error messages for minLength or isNumeric validations.

**Comment by MilosRasic** [comment]
Could be a bug but the codepen is using an older version of Formsy and a mixin, not a HOC, to implement a a custom component. Please make sure you are using the latest version so that we don't end up chasing a bug that's already been fixed.

**Comment by rkuykendall** [comment]
I would also try seeing if the error is still present if you use object-style validations. Then we would know if it is caused by the string-validations-parser. I actually didn't know you could join them with commas and add arguments with colons like that. That part of the code may need additional testing.

**Comment by vikasrohit** [comment]
Thanks @rkuykendall for pointers. I tried object styled validations as well. Same results. However, I did found one issue with my pen, it was using lodash which was not imported yet in the pen. However, the question is that any error in custom validation should be reported back, right? Right now it seems to be silently ignored.

Despite fixing the issue with my custom validator, I have the issue. It does not show the validation message for my custom validation once user makes the field dirty. The validation do appear on first load, though. I found a fix for this as well, if I return explicit `boolean` values from my validator, it works fine. I have updated the pen to reflect the same. Just remove ` ? true : false` from line#3 of the JS and you would see the error. Is it a bug or again its the way I am using it.

**Comment by rkuykendall** [comment]
Okay, let me see if I can get this straight:

- **Issue:** Custom validation was throwing error, but Formsy fails silently
- **Issue:** Custom validation must return explicit boolean values or it is ignored

Is that correct? And is it correct that you've now resolved all issues with your code? If so, I think my next step would be to write failing tests for the above 2 issues and then fix them in the code. I feel like the first one shouldn't be considered a 'fail' but should instead not swallow the error so the user can fix it ( which is what it sounds like is happening ).

**Comment by vikasrohit** [comment]
Correct @rkuykendall That is what I think issues are.

> but should instead not swallow the error so the user can fix it ( which is what it sounds like is happening ).

I think it is swallowing the error. I didn't found the error in the console, its only by trial and error, I found the error. Might me I haven't used it properly.

**Comment by rkuykendall** [comment]
Hm, unfortunately there are no try-catch blocks anywhere significant in the code, just around some JSON parsing. I might test throwing an error in a validator locally, but it _should_ be showing.

**Comment by MilosRasic** [comment]
I rewrote the codepen with latest version of formsy-react. Couldn't properly include it in a codepen (this may be a case for more build targets in the npm package) so I made a repo https://github.com/MilosRasic/formsy-test

As detailed https://github.com/formsy/formsy-react/blob/master/API.md#getErrorMessages, the example is working as expected. getErrorMessage() returns only a single error. You should use getErrorMessages() when you expect multiple validation errors.

This part of the API is a bit confusing. Maybe we should consider removing getErrorMessage() and telling users to always use getErrorMessages()?
