### ISSUE TITLE
Using Deprecated State Methods

### ISSUE THREAD

**Issue by dlewis-irse** [formsy/formsy-react#213]
Receiving the following alerts in the the console
![image](https://user-images.githubusercontent.com/28788217/63068093-d05bf400-bec6-11e9-95c4-1a1059a04df2.png)

**Comment by rkuykendall** [comment]
Thanks for the issue! Looks like we only have 1 in the source and 1 in a test:

https://github.com/formsy/formsy-react/search?q=componentWillReceiveProps&unscoped_q=componentWillReceiveProps

**Comment by dlewis-irse** [comment]
Thanks for the response - just to clarify it looks like the errors are for :
ComponentWillMount
ComponentWillReceiveProps
ComponentWillUpdate

https://github.com/formsy/formsy-react/search?q=ComponentWillMount&unscoped_q=ComponentWillMount			
https://github.com/formsy/formsy-react/search?q=ComponentWillReceiveProps&unscoped_q=ComponentWillReceiveProps
https://github.com/formsy/formsy-react/search?q=ComponentWillUpdate&unscoped_q=ComponentWillUpdate

Also I never knew you could search a repo like that - thanks for helping me discover an obvious feature of GitHub

**Comment by wkerswell-gresham** [comment]
Hey, I see the PR was merged into master but I still see the warning. Was it released? I am using 1.1.5 published to NPM

**Comment by SHA-4** [comment]
Hey @wkerswell-gresham, it looks like this is part of the active development work of the 2.0.0 beta. See [the README](https://github.com/formsy/formsy-react/blob/master/README.md#join-the-2x-beta) and the relevant [beta pre-release](https://github.com/formsy/formsy-react/releases/tag/v2.0.0-beta.5)
