### ISSUE TITLE
Unable to call mock function onValidSubmit using Jest with Enzyme

### ISSUE THREAD

**Issue by pradok** [formsy/formsy-react#23]
Hi
I am passing in `jest.fn()` as a prop eg. `<Formsy.Form onValidSubmit=jest.fn()>`.
Using Enzyme's `Component.simulate('submit');` where Component is shallow, Jest says, "But it was not called."

Not sure what's the best way to simulate form submit for Formsy.

**Comment by twisty** [comment]
Are you using a `1.x` release? (`<Formsy.Form>` is now `<Formsy>`).

Can you show some of the code in the test that is causing you problems?

If it helps, part of the formsy test that checkes for a form submission is here:

https://github.com/formsy/formsy-react/blob/9bc54ef4e4104a6daa1d3a7f95c97b9a3ad97792/tests/Formsy-spec.js#L571-L590

**Comment by rkuykendall** [comment]
Hey @pradok! Any word on this? I'd love to help, and don't want to let unconfirmed bugs sit too long.

**Comment by pradok** [comment]
@rkuykendall Apologies! I am not using 1.x release now, so all good as suggested by @twisty. Thanks
