### ISSUE TITLE
Failed prop type: The prop `name` is marked as required in `Formsy(Component)`, but its value is `undefined`

### ISSUE THREAD

**Issue by hanbar** [formsy/formsy-react#241]
In previous version (0.19.5) I had `<MyInput />` without the required name property, which was ok, because in the parent component I render `<MyInput />` by React.cloneElement where the name is cloned from key prop. In the latest formsy-react there are plenty of warnings

> Failed prop type: The prop `name` is marked as required in `Formsy(Component)`, but its value is `undefined`

in the console. Am I supposed to manually go through the whole application and fill the missing prop?

**Comment by rkuykendall** [comment]
Since name is how we run everything I think this is probably a good change? We use find by name for everything.

But you're saying you DO have name, it's just that it's getting added later so Formsy isn't seeing that?

**Comment by hanbar** [comment]
Yes, name is added in the parent Form component during React.cloneElement(child, { name: child.key }); and then rendered. Simplified, the code looks like this:

````
class Page extends React.Component {
	render() {
		return (
			<Form
				onValidSubmit={this.handleValidSubmit}
				onInvalidSubmit={this.handleInvalidSubmit}
				onChange={this.formChanged}
			>
				<Text
					key={"unique"}
					value={componentValue}
					validations={validations}
					validationErrors={valErrors}
				/>
			</Form>
		);
	}
}

class Form extends React.Component {
	render() {
		const components = [];

		React.Children.forEach(this.props.children, (child, i) => {
			const formComponent = React.cloneElement(child, { name: child.key });
			components.push(formComponent);
		});

		return <Formsy {...formProps}>{components}</Formsy>
	}
}
````

**Comment by rkuykendall** [comment]
I think your issue is not with Formsy, but with prop-types: https://github.com/facebook/react/issues/6653

**Comment by rkuykendall** [comment]
@hanbar Please re-open if you still think this is an issue with Formsy and not React, as described in the linked issue.
