### ISSUE TITLE
Binding for `isFormSubmitted` missing

### ISSUE THREAD

**Issue by krazi3** [formsy/formsy-react#25]
The binding for `isFormSubmitted` is missing at https://github.com/formsy/formsy-react/blob/v1.1.0/src/Wrapper.js#L62.

It is giving the following error.
![image](https://user-images.githubusercontent.com/6938697/33074702-fd0fb420-cee8-11e7-9514-2fd7e7f519e0.png)

**Comment by krazi3** [comment]
I have seen that the `master` branch has the required changes. If we can push it to `npm`.Thanks.

**Comment by rkuykendall** [comment]
@krazi3 Thanks! Yes, planning on pushing a 1.1.1 release out today.

**Comment by rkuykendall** [comment]
@krazi3 Thanks! Yes, planning on pushing a 1.1.1 release out today.

**Comment by rkuykendall** [comment]
@krazi3 @zabute Sorry, got busy yesterday evening. 1.1.1 is now released!
