### ISSUE TITLE
The Formsy didn't show error message when the input left blank

### ISSUE THREAD

**Issue by hungbang** [formsy/formsy-react#258]
The `Formsy` didn't show error message when the input left blank, even I did set the `required ` for the input

**Comment by hungbang** [comment]
Who anyone can help this issue? Thank you in advance !

**Comment by hungbang** [comment]
Solved by 
`blurValue = event => {
    this.props.setValue(event.currentTarget.value);
    if (this.props.onBlur) {
      this.props.onBlur(event);
    }
  };

  keyDown = event => {
    if (keycode(event) === 'enter') this.setValue(event.currentTarget.value);
    if (this.props.onKeyDown)
      this.props.onKeyDown(event, event.currentTarget.value);
  };`
.....

`const {
      isRequired,
      isPristine,
      isValid,
      showRequired,
      validationErrors
    } = this.props;

    const isRequiredError =
      isRequired() &&
      !isPristine() &&
      !isValid() &&
      showRequired() &&
      validationErrors.requiredError;

    const errorMessage = this.props.getErrorMessage() || isRequiredError;
    const value = this.props.getValue() || '';

    return (
      <TextField
        {...importedProps}
        onChange={this.changeValue}
        onBlur={this.blurValue}
        onKeyDown={this.keyDown}
        value={value}
        error={Boolean(errorMessage)}
        helperText={errorMessage}
      />
    );`

**Comment by th3fallen** [comment]
This is actually occuring for us too on v2. seems like an oversight to supress the error message when required is set to true.
