### ISSUE TITLE
Life cycle wrongly named

### ISSUE THREAD

**Issue by Knupp15** [formsy/formsy-react#261]
Warning: Formsy(EmailInputBase) has a method called componentDidUnmount(). But there is no such lifecycle method. Did you mean componentWillUnmount()?

**Comment by rkuykendall** [comment]
This seems VERY likely. Thank you for noticing this!

**Comment by kirbydcool** [comment]
Oops that's my bad. I was a little too hasty with that pr. I'll add a fix and add some testing around the unmount behavior.

**Comment by mrnav90** [comment]
@kirbydcool 
Could you please help fix soon. I need to update new version for resolve error :(
Thanks

**Comment by kirbydcool** [comment]
Yeah sorry I've been busy at work. Will hopefully get to it today.
