### ISSUE TITLE
lifecycle hook name change from componentDidUnmount to componentWillUnmount not updated in dist folder

### ISSUE THREAD

**Issue by shravya95** [formsy/formsy-react#283]
hello the dist folder of latest master is not updated. Lifecycle hook name fix(https://github.com/formsy/formsy-react/pull/282) from componentDidUnmount to componentWillUnmount is not  reflected in https://github.com/formsy/formsy-react/blob/master/dist/formsy-react.cjs.js#L1816

**Comment by darkcattz** [comment]
Hello, Same problem for me. It's possible to create a new tag for the beta ?

**Comment by rkuykendall** [comment]
A release has been done, thanks for the reminder!

https://github.com/formsy/formsy-react/releases/tag/v2.0.0-beta.7

Since you both seem to be following the beta, how do you feel about a 2.x release now? Trying to decide when to pull that trigger.

**Comment by darkcattz** [comment]
Thank you.
I am currently testing to see if everything is ok with last version of React and I am giving you my opinion :)

**Comment by darkcattz** [comment]
Tested all of my forms right now. From my side, everything seems OK for V2 ;)
React JS : 16.12
Material UI : 4.8.0

Thanks again

Thanks again
