### ISSUE TITLE
Contributor communication?

### ISSUE THREAD

**Issue by MilosRasic** [formsy/formsy-react#29]
How about using some chat platform and keeping github issues for stuff relevant to the code? I prefer Discord myself because I use it a lot and it's free and easy to set up, but I can use anything else, whatever you guys prefer.

**Comment by rkuykendall** [comment]
Sounds good to me. I know Gitter is pretty popular for Github projects to have, but I'm cool with whatever. Would this work well asynchronously? I kinda like being able to get up-to-date with Formsy once or twice a day, or whenever I'm free.

**Comment by MilosRasic** [comment]
I don't see why it shouldn't. I doubt we'll have a reason to urgently bug you about a react form library several times a day every day :)

**Comment by rkuykendall** [comment]
Temporary fix while we set this up:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/796717/33136369-07dc25ca-cf73-11e7-8c80-9d9e01e6d641.png">

**Comment by rkuykendall** [comment]
Added https://dependabot.com/ to open PRs when our libraries update, and keep us from falling behind or having to remember to check outdated.

**Comment by apuntovanini** [comment]
I'm cool with anything as well, and I think it's a really good idea to set it up

**Comment by MilosRasic** [comment]
Yeah, I'm kinda conflicted about it. On one hand it makes a PR and tests are ran so you're pretty sure the library is ok with the new version (or as ok as your tests are good). On the other hand, yeah, it's a mess.

**Comment by apuntovanini** [comment]
https://gitter.im/formsy

**Comment by rkuykendall** [comment]
@Semigradsky @MilosRasic Good point. Actually didn't think this project would get so many updates. Changed to monthly.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/796717/33438152-f8a97508-d5b7-11e7-827f-963473439695.png">

**Comment by rkuykendall** [comment]
If that's still annoying we can remove it, and just do library bumps when people report issues with outdated dependencies, but I don't think that's the best system.

**Comment by maccuaa** [comment]
I agree, best to stay on top of our dependencies instead of letting them get stale.  I think letting it run monthly should definitely help with the spam of PRs we've been getting.  It'd be nice if there was an option for it to update more one dependency at a time but it doesn't look like they support that.

**Comment by MilosRasic** [comment]
Resolved.
