### ISSUE TITLE
Port issues from original repo

### ISSUE THREAD

**Issue by aesopwolf** [formsy/formsy-react#32]
Stumbled across this and thought it might be useful here.

https://probot.github.io/apps/move/

**Comment by rkuykendall** [comment]
I thought about doing something like that, but going through the issues you find most of them are so old the original posters would likely just be annoyed to be getting notifications some 8+ months later. I'd say at most we should make a generic "project no longer dead, check out over here if interested" comment on all of them.

**Comment by th3fallen** [comment]
i'd say we should start as a clean break, if they're still valid issues someone will recreate them.

**Comment by mbrookes** [comment]
If the formsy-react repo had been transferred instead of cloned, this would have happened automatically.

**Comment by MilosRasic** [comment]
@mbrookes We couldn't reach the original author. Of course a transfer was preferable, but there was nothing we could do.

**Comment by mbrookes** [comment]
@MilosRasic Ah, okay, I assumed the "Moved" message in the README meant he was involved, but of course a contributor could add that without owner involvement.
