### ISSUE TITLE
prefer wrapper component to addValidationRule

### ISSUE THREAD

**Issue by Graham42** [formsy/formsy-react#35]
I'm not a fan of the way `addValidationRule` acts as a side effect. Would prefer to pass validators to the `Formsy` component or some other `FormsyProvider` type component instead. This way validators would be scoped and not affect the global state of formsy.

As part of solving this, I'd recommend deprecating `addValidationRule`

**Comment by MilosRasic** [comment]
I like how you can register validators globally and use them anywhere in the project. Working on a project with 30+ forms, it really helps a lot.

If you have field- or form-specific validators, you can always pass them directly to a field as a function and not have them registered globally.

**Comment by Graham42** [comment]
Whoops, was definitely meaning to include that case. I'll expand my thought on the `FormsyProvider` component. (name totally open for discussion)

`FormsyProvider` would give a global way to set up custom validators etc. In a similar concept to the [redux `Provider` component.](https://redux.js.org/docs/basics/UsageWithReact.html)

```jsx
ReactDOM.render(
  <FormsyProvider validators={myCustomValidators}>
    <App />
  </FormsyProvider>
);
```

**Comment by rkuykendall** [comment]
A provider seems like an interesting middle ground, but I think Milo's point that you don't need to register your validators globally a very strong one.

Closing this as it's not something anyone is currently promoting or working on, and I want to keep the tickets clean. If anyone is interested in continuing to discuss this ticket please re-open!
