### ISSUE TITLE
Update Wrapper props like showRequired to values not functions

### ISSUE THREAD

**Issue by rkuykendall** [formsy/formsy-react#38]
Title pretty much covers it. I keep getting render bugs with mobx, I think due to no props technically changing when the results of those functions change. So I was wondering if anybody here knew why that was the way it worked.

I'm going to write a wrapper that passes the values of those functions as props and see if that fixes the issues I've been having.

**Comment by MilosRasic** [comment]
Looks like a left-over design choice from when Wrapper was a mixin. Now that it's a mixin, I don't see why they shouldn't be props. 

We gotta be careful with changing the existing API though. I'd suggest adding props and deprecating functions with warnings for 1.2, and planning for a future 2.0 release where we can remove everything that's deprecated.  I don't have much experience with a semver that makes sense though. Anyone have a better idea?

**Comment by rkuykendall** [comment]
Sorry, I meant for my own project, just to test out the idea / debug. I definitely wouldn't propose a Formsy change like that so nonchalantly 😛 

That makes a lot of sense, the mixin thing. Good point.

**Comment by MilosRasic** [comment]
Well, it really makes sense to change those functions to props. We're no longer stuck with a mixin.

**Comment by twisty** [comment]
We've taken the following route in `formsy-react-components`: where needed we just call the function in our HOC and pass the result as the prop (so function `getErrorMessages` becomes array `errorMessages`) -- it's more apparent to see what's changing. Where we have passed the functions through we've used the "`on` prefix" convention, so `setValue` becomes `onSetValue`, etc.

https://github.com/twisty/formsy-react-components/blob/8a473cd911e31e01fd6e66d9d727e6c421960ec0/src/hoc/component.js#L110-L127

**Comment by rkuykendall** [comment]
Made a proposal for what this type of change in Formsy might look like. Would love feedback: https://github.com/formsy/formsy-react/pull/50 -  [src/Wrapper.js](https://github.com/formsy/formsy-react/pull/50/files#diff-4597c2f0aa0f499ddf5d84301e45671aL171)

**Comment by MilosRasic** [comment]
#50 merged into v2.0
