### ISSUE TITLE
Infinite loop when comparing regular expressions

### ISSUE THREAD

**Issue by mattmcdonald-uk** [formsy/formsy-react#399]
When `isSame` is called with a regular expression, they are tested using `a === b` comparison.

As regular expressions are passed by reference these are never equal and causes an infinite loop within `componentDidUpdate`.

**Comment by rkuykendall** [comment]
Re-opening until release.

**Comment by rkuykendall** [comment]
The fix is merged and will be released with 2.0.2.

**Comment by rkuykendall** [comment]
This was fixed in version 2.0.2:

# v2.0.2

- Unify definition of empty value; Clean up validation rules (#402)  465fd21
- Improve typing of Element tests (#401)  05bea58
- Test for regex equality (#400)  4265967

https://github.com/formsy/formsy-react/compare/v2.0.1...v2.0.2
