### ISSUE TITLE
Form method getCurrentValues issue for date input

### ISSUE THREAD

**Issue by DeveloperUA** [formsy/formsy-react#403]
Form method **gerCurrentValues** for date input returns an empty object instead of the value itself.
Looks like the **cloneIfObject** does not work properly with checking if value is an object or not (treats date like an object) and then clones it.

**Comment by rkuykendall** [comment]
Good news! You weren't the only one and this should have been fixed in 2.0.1. Let me know if you're on the latest version and still experiencing this problem.

**Comment by rkuykendall** [comment]
@DeveloperUA Closing this as I believe it has been fixed. *Please re-open* if this issue persists in 2.0.2.
