### ISSUE TITLE
Allow validation errors in UpdateInputsWithError method to be React element

### ISSUE THREAD

**Issue by helluvalazyass** [formsy/formsy-react#455]
Strings in error messages works fine. But if the error message is a little complex and involves HTML tags (e.g. links), then I am not able to set the error message as it only allows string.
If there is any other way to set error messages that may contain HTML tags, please let me know.
Thanks.

**Comment by rkuykendall** [comment]
That seems very valid! `React.ReactNode` would probably be the best option instead of `Array<string | Element>`, since it covers anything that can appear on the page. I can't, from memory, think of any reason this wouldn't be possible. It's likely just necessary for someone to change the types.

**Comment by rkuykendall** [comment]
Released in [formsy-react v2.0.3](https://github.com/formsy/formsy-react/releases/tag/v2.0.3)! Thank you for this improvement.

**Comment by helluvalazyass** [comment]
Thanks!
