### ISSUE TITLE
Value question

### ISSUE THREAD

**Issue by th3fallen** [formsy/formsy-react#46]
First off thanks so much for reviving this great project.

My question is did you guys fix the getValue bug that required us to do stuff like this
`value={ typeof this.props.getValue() === 'undefined' ? '' : this.props.getValue() }`
or `value={ this.props.getValue() || '' }`

**Comment by rkuykendall** [comment]
Nobody currently active here worked on the 1.0 rewrite, so I'm not sure. Only way to find out would be to test it. What was the issue that would present if you didn't do that?

**Comment by th3fallen** [comment]
lol i honestly dont remember what the bug was but i'll remove my fix and see...

**Comment by th3fallen** [comment]
looks to be fixed now i swear this new version is like christmas!
