### ISSUE TITLE
Form onchange not converting dot notation

### ISSUE THREAD

**Issue by th3fallen** [formsy/formsy-react#47]
As seen in the docs a form input with a name of `foo.bar` will result in `{foo: { bar: VALUE}}` but when using the `onChange` on the form itself the returned object is not honoring that.

**Comment by th3fallen** [comment]
from looking deeper looks like https://github.com/formsy/formsy-react/blob/master/src/index.js#L55 needs to call `mapModal`

**Comment by maccuaa** [comment]
If you have time could you open a Pull Request with the fix and add some tests to verify the behavior?

**Comment by th3fallen** [comment]
done

**Comment by rkuykendall** [comment]
Is this how pre-1.0 releases worked? I thought I remembered onChange always returning flat, and then having to call getModel inside the function to get the nested. I could see this being a more sensible way for this to work, but if this is changing long established functionality, we should consider it and do a version bump / document the change well.

**Comment by th3fallen** [comment]
Until today i had no idea pre 1.0 had an onChange method... good call on the version bump, my main goal for this change was to stay consistent with the submit functionality since if any person is using dot notated names they expect them to be nested.

Is there a way to call `getModal` without needing a ref?

**Comment by rkuykendall** [comment]
No, I had to use a ref. I did always think it was stupid onChange formatted the data differently. I could get behind this change. It would be an API-breaking one though, so we'd need to make a fuss about it.

**Comment by th3fallen** [comment]
lets do it!

**Comment by rkuykendall** [comment]
I think our two options are `1.2.0` and `2.0.0`. Either way we can use this to close https://github.com/formsy/formsy-react/issues/27. If we go for `2.0.0`, I'd like us to consider also addressing https://github.com/formsy/formsy-react/issues/38 with that update. I've made a PR with my initial thoughts there.

**Comment by maccuaa** [comment]
Makes sense to me.  Makes it easier to reason about the components you're writing when the props come in as values instead of functions.

**Comment by MilosRasic** [comment]
merged #48 into v2.0
