### ISSUE TITLE
Slow startup time on forms with many inputs

### ISSUE THREAD

**Issue by felixmosh** [formsy/formsy-react#471]
I have a large form (100+ checkboxes) on one of my pages, it takes more then 3 sec to initial render it. After the initial render it works properly.
I've checked what make it stuck, and looks like that the `attachToForm` method which each input is calling on mount and it triggers validation for each insert, maybe it is better to debounce the call for `form`.
`attachToForm -> validate(Input) (which calls to setState) -> validateForm (which calls to setState)`

This chain of calls means that there are many formValidation (Arithmetic progression) which is redundant, cause onMount of the form it self there another call for `validateForm`

![image](https://user-images.githubusercontent.com/9304194/81476551-232ac800-921b-11ea-83a0-71ef2da8f03c.png)
My test page: https://codesandbox.io/s/awesome-taussig-2c1c4

**Comment by felixmosh** [comment]
I've made a simple change, added a field which starts as `false` and changes to `true` on form `componentDidMount`.

run it on local machine:
Before:
![image](https://user-images.githubusercontent.com/9304194/81480635-950f0b80-9233-11ea-8e8b-c73cfd3c74fe.png)

After: 
![image](https://user-images.githubusercontent.com/9304194/81480661-c12a8c80-9233-11ea-8549-4dee8fc33756.png)

**Comment by rkuykendall** [comment]
Debouncing makes sense. This seems like a really fun project. I might try it if nobody else gets around to it. How did you test your performance changes? I'm wondering if a simple .html "performance test suite" could be written which uses the UMD build?

**Comment by felixmosh** [comment]
I've downloaded the zip from codesandbox, and `yarn link` the lib

**Comment by felixmosh** [comment]
I've another path to fast render... there is redundant update due to call of the `attachToForm` onMount which changes the state of the component, I think that If the `attachToForm` will be called in the constructor and will return the initial state of the component this will improve start-up time.

Will experiment with this idea :]

**Comment by felixmosh** [comment]
Improved by #490
