### ISSUE TITLE
On load functionality

### ISSUE THREAD

**Issue by glebdv** [formsy/formsy-react#473]
I just had a quick proposal - maybe adding a OnLoad fucntionality to Formsy wrapper, Sometimes it takes a little bit for Formsy to load on large forms, so would be nice to be able to do something while it loads (I have a 100+ fileds form). 
Something more of a isLoaded prop? 

Other than that, I really like Formsy! You guys did an amazing job on this library, and it's super popular in the dev world which - koodos!

**Comment by rkuykendall** [comment]
Interesting idea! We also have ideas for improving the load time of Formsy on large forms: https://github.com/formsy/formsy-react/issues/471

**Comment by rkuykendall** [comment]
@glebdv Mind trying the newest build on your 100+ input form? If it's better, I'd love to close this issue.
