### ISSUE TITLE
How to avoid validation on initialization.

### ISSUE THREAD

**Issue by zgayjjf** [formsy/formsy-react#52]
I hava a form with `validationErrors validations` props. However, the error message will display when form is mounted, before users' input.
How can i run validation only on users input, not on initialization.

I notice that validations will be run in two place on initialization: 
1. When Formsy mounted.
2. Every time a field is attacted to Formsy.

[https://github.com/formsy/formsy-react/blob/master/src/index.js#L210](https://github.com/formsy/formsy-react/blob/master/src/index.js#L210)

[https://github.com/formsy/formsy-react/blob/master/src/index.js#L35](https://github.com/formsy/formsy-react/blob/master/src/index.js#L35)

Could there be a config to solve this problem?

**Comment by rkuykendall** [comment]
I would check out the `showError()` prop. You can see a snippet of some of my input code, as well as a link to a great repo, [here](https://github.com/formsy/formsy-react/issues/51#issuecomment-353434613).

**Comment by MilosRasic** [comment]
Inactive and resolved. Closing.
