### ISSUE TITLE
Build error: 'PassDownProps' is not exported by src/interfaces.ts, imported by src/index.ts

### ISSUE THREAD

**Issue by rkuykendall** [formsy/formsy-react#528]
This is preventing a release.

Reproduction: Run `yarn build`

**Comment by rkuykendall** [comment]
I think this is caused by the JS build pipeline trying to import something that isn't there because it's a type which is not included in the transpiled JS. I find the closer a type gets to index.ts the more it causes issues like this.

**Attempts to fix:**
- Bumping all libraries ❌ 
- Moving the offending type to `interfaces.ts` ❌ 
- Converting it from a "type" to an "interface" ❌ 

Ideas for future work:
- See how far back in commits you must go to fix build
- Move more code OUT of index.ts, and make it a pure re-exporting file? This actually might be a great improvement, since that's not a descriptive filename.

**Comment by felixmosh** [comment]
What do you think about start using [tsdx](https://github.com/formium/tsdx)?

**Comment by rkuykendall** [comment]
Yeah that actually looks great. Give it a kick.

**Comment by felixmosh** [comment]
I've found the issue, seems that the `PassDownProps as FormsyInjectedProps` in `index.ts`.
After that there is another ```[!] Only inline sourcemaps are supported when bundling to stdout.```

**Comment by rkuykendall** [comment]
Thanks! v2.1.0 published. Fantastic changes.

https://github.com/formsy/formsy-react/releases/tag/v2.1.0
