### ISSUE TITLE
Console error: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()

### ISSUE THREAD

**Issue by vitaliyhayda** [formsy/formsy-react#542]
After updating from 2.0.0 to 2.1.0 I'm getting the following error in console:
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()

**Comment by felixmosh** [comment]
@vitaliyhayda, can you add some minimal example which reproduces this? 
codesandbox.io can be really helpfull.

**Comment by rkuykendall** [comment]
@vitaliyhayda Please re-open this issue if you are able to build an example or provide us more information.
