### ISSUE TITLE
Set errors from withFormsyProps

### ISSUE THREAD

**Issue by glebdv** [formsy/formsy-react#544]
We're using Formsy in our company (great lib guys!) and I ran into a little issue while trying to add an intermediate validation. 
We have something like this: `<ParentsComponent/>` renders `<DatepickerField/>` which renders `<MaskedInput/>`.

Parent component uses 
`<Formsy>
    {children}
    <DatepickerField />
<Formsy/>`
 and passes `validations={{...}}` and `validationErrors={{...}}` to detepickerField which is wrapped in `withFormsy` 

I'm trying to add a validation within `datepickerField`, to make sure the entered date is valid, but I see no way to do it using `withFormsy` props. 
Something like 
`<MaskedInput`
`validations={{ ...this.props.validations, isDate: true }}`
`validationErrors={{...this.props.validationErrors, isDate: "Please enter a valid date" }}`
`/>`

That doesnt work, and it would be great to be able to add a validation rule outside of component props by using a function/hook?
something like `setFieldValidation(validations, validationErrors, fieldName)` which could then be used the same as above:

> useEffect( () => {
>
>   const { name, validations, validationErrors } = this.props
>   const groupValidations = { ...validations, isDate: true }
>   const groupErrors = { ...validationErrors, isDate: "Please enter a valid date" }
>
>   setFieldValidation(groupValidations , groupErrors , name)
>
> }, [] ) //or it's componentDidMount alternative

If I legit missed a way of setting extra validation rules from the Formsy props, then I do apologize profusely. If that's the case, could someone point my mind to the right spot? Ty!! Cheers gents and ladies!

**Comment by felixmosh** [comment]
I'm not sure I get the scenario. can you elaborate? maybe add some codesandbox?
