### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by loan-laux** [formsy/formsy-react#583]
I'm updating [`segmented-control`](https://github.com/lorensr/segmented-control) to React 17 and would need Formsy to support it as well.

There must be a lot of community members who are starting to need React 17 support for their own projects too.

I tried to work on it but quickly got stopped in my tracks because `airbnb-prop-types` still requires React 16, although that's about to change soon [thanks to this PR](https://github.com/airbnb/prop-types/pull/74).

Just filing this issue to:

1. Track progress of React 17 support on `airbnb-prop-types`
2. For anyone else to work on React 17 support themselves if I don't have time to do it

**Comment by rkuykendall** [comment]
Cool. I checked `airbnb-prop-types` in our yarn.lock, and it's from `enzyme-adapter-react-16`, which is just for testing. So are you sure that formsy production ISN'T React 17 compatible?

If anything, we'd need to wait for the new `enzyme-adapter-react-17` which you can follow here: https://github.com/enzymejs/enzyme/issues/2429

**Comment by felixmosh** [comment]
I'm using `React 17` with the latest `formsy-react` it works fine for 2 month, the only thing that is popped up is the peerDependency warning

**Comment by loan-laux** [comment]
Indeed. I can confirm that it works well. Sorry about the confusion here, I was initially confused by this peer dependency warning. Looking forward to your PR being merged @felixmosh. Can you add `Fixes #583` so that it automatically closes this issue?

**Comment by felixmosh** [comment]
Published in v2.2.2
