### ISSUE TITLE
updateInputsWithValue doesn't update nested field

### ISSUE THREAD

**Issue by adsee42** [formsy/formsy-react#591]
```js
  public updateInputsWithValue: IUpdateInputsWithValue<any> = (values, validate) => {
    Object.entries(values).forEach(([name, value]) => {
      const input = this.inputs.find((component) => component.props.name === name);

      if (input) {
        input.setValue(value, validate);
      }
    });
  };
```

For form fields like:
```
// data
{
  address: {
    postalCode: "xxx",
    city: "xxx"
  }
}
// field
```js
<MyInputComponent name="address.postalCode"/>
<MyInputComponent name="address.city"/>
```
`updateInputsWithValue` does not work.

**Comment by rkuykendall** [comment]
This is a great catch, @adsee42! If you have a moment, want to review this PR which includes the code change and a test, to make sure I've understood correctly?

https://github.com/formsy/formsy-react/pull/596

**Comment by adsee42** [comment]
This bug seems to be fixed, but may be it's just me, when doing:
```javascript
formRef.current.updateInputsWithValue({
  profile: {
    firstName: "f",
    lastName: "l"
  }
})
```
nothing updated.

To update, I have to use:
```javascript
formRef.current.updateInputsWithValue({
  "profile.firstName": "f",
  "profile.lastName": "l"
})
```

Is this the intended behavior?

**Comment by adsee42** [comment]
https://codesandbox.io/s/tender-ramanujan-jhmqy?file=/src/form.js

No, the code worked.

So it may be a problem of my lodash version.

Anyway this bug is fixed!
Nice work!

**Comment by rkuykendall** [comment]
Thanks, @adsee42!
