### ISSUE TITLE
Deprecation of React.PropTypes

### ISSUE THREAD

**Issue by rkuykendall** [formsy/formsy-react#6]
Original issue: https://github.com/christianalfoni/formsy-react/issues/438

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by apuntovanini** [comment]
Seems to be already fixed in master, isn't it? Can't find any reference of React.PropTypes anymore

**Comment by rkuykendall** [comment]
I believe it is, but since we haven't had a release with the fix yet, I don't think this issue can counted as solved for users yet. As for why I re-created it here, it's the third most popular issue on the original repo by reactions.

**Comment by apuntovanini** [comment]
Ok, I get it, well done replicating this issue here, helps with tracking things to do

**Comment by MilosRasic** [comment]
Latest release is fully migrated to prop-types and tested in a real project. Closing this.
