### ISSUE TITLE
updateInputsWithValue does not prefill the form with provided data

### ISSUE THREAD

**Issue by onyxolu** [formsy/formsy-react#605]
I am trying to prefill a formsy form with data onClick of an edit button but it only updates the form value and doesn't prefill the inputs

**Comment by rkuykendall** [comment]
Are you able to provide a working mini-example of this? There may be an issue with the inputs I would be happy to look at.

**Comment by onyxolu** [comment]
Yes

in My userForm component

  constructor(props) {
    super(props);
    this.userForm = React.createRef();
  }

  componentDidMount() {
    const { currentUser, upsert_action } = this.props;
    if (upsert_action == "update") {
      this.userForm.current.updateInputsWithValue(currentUser, true);
    }
  }

          <Formsy
            onValidSubmit={this.submit}
            ref={this.userForm}
          >
           <MyInput name="username"/>
          </Formsy>



MyInput Component

class InputValidation extends React.Component {

  changeValue(event) {
    this.props.setValue(event.currentTarget.value);
  }

    return (
      <div className={this.props.className}>
        <input
          type={this.props.type}
          name={this.props.name}
          id={this.props.id}
          className={"form-control"}
          onChange={this.changeValue}
          placeholder={this.props.placeholder}
        />
        {required}
        {errorList}
      </div>
    );
}

export default withFormsy(InputValidation);

**Comment by rkuykendall** [comment]
I don't see you setting `value={this.props.value || ''}` in your input like in [the example](https://github.com/formsy/formsy-react#1-build-a-formsy-element), which I think is the issue.

**Comment by onyxolu** [comment]
Thank you so much @rkuykendall  That was my issue and it works very fine now

**Comment by rkuykendall** [comment]
Glad I could help!
