### ISSUE TITLE
Number validation issue

### ISSUE THREAD

**Issue by matteo1010** [formsy/formsy-react#61]
Hi, 
I use Formsy and I have a issue when try to validate the number.
If I load the field with number, the button still disable. If the field receive an input the button become enable.

    <Formsy onValidSubmit={this.BuildMethod.bind(this)} onValid={this.enableButton.bind(this)} onInvalid={this.disableButton.bind(this)}>
	    <div className="main__container">
	   
		<NumericSectionField ref="Percentage" metadata={this.props.metadata.metadatas.filter(x => x.name == "Percentage")[0]}
			fieldValue={this.props.percentage} />
	    </div>
	    <div>
		<button type="submit"
			className={this.state.canSubmit ? "button-text--right" : "button-text--right button-disabled"}
			disabled={!this.state.canSubmit}>
			{this.props.unitEditing ? "Edit" : "Save"}
		</button>
	    </div>
    </Formsy>

Thanks

**Comment by MilosRasic** [comment]
I don't see any validators on your NumericSectionField so the form should always be valid. Can you debug and check if enableButton and disableButton are actually being called after the component initially mounts?

**Comment by matteo1010** [comment]
Thanks
