### ISSUE TITLE
Validation `values` 'undefined' with 'defaultValue' set

### ISSUE THREAD

**Issue by DamonBlais** [formsy/formsy-react#642]
Hello!

So, I have a lengthy, multi-page form that I've used LocalStorage to save the state therein.

```ts
const [state, setState] = useState<AccountSetupForm>({} as AccountSetupForm)

// Load from LocalStorage on Page Load
useEffect(() => {
  const savedState = window.localStorage.getItem(LSKEY_ACCOUNT_SETUP_FORM)
  if (savedState) {
    setState({ ...state, ...JSON.parse(savedState) })
  }
}, [])
```

However, when I restore the state to the form (which updates its values), the validation doesn't see this.

The `Next/Submit` button in the form is disabled on load, even if all fields were populated on load.

```tsx
const [disabled, setDisabled] = useState<boolean>(false)
return (
  <Form
    onValid={() => setDisabled(false)}
    onInvalid={() => setDisabled(true)}
  >
    {/* ... */}
  </Form>
)
```

Then, upon editing any field, only that field is defined in the validation, all else are `undefined`.

```ts
addValidationRule('isPhone', (values: Values, value?: string): boolean => {
  console.log(values) // only the field I edited is defined, everything else is `undefined`
  setState(values) // is there a better way to access the form state than inside a validator?

  if (value) {
    const code = values['phone-country-code']
    if (code) { // <-- `code` is `undefined` even though its field has a `defaultValue`
      return validator.isMobilePhone(
        `${code.slice(0, code.indexOf(':'))}${value}`,
        'en-US',
        {
          strictMode: true,
        }
      )
    }
  }

  return false
})
```

How do I tell the validation to grab the values of all the fields after I've loaded them?

---

Example Form Input (for completeness of reproducability sake):

```tsx
<Form.Input
  autoComplete="email"
  defaultValue={state.Email}
  label="Email Address"
  name="email"
  type="email"
  
  {/* Had to wrap this because idk how to access values except in a validator */}
  validations="isEmailWrapped"

  validationErrors={{
    isEmail: 'Doesn\'t look like a valid email address...',
  }}
  errorLabel={errorLabel}
/>
```

**Comment by DamonBlais** [comment]
If the user triggers an edit (deletes and re-types a character) **in every field**, then the form realizes all the inputs have values, and re-enables the `Next/Submit` button as expected. `formsy-react` is working EXCEPT for it ignoring `defaultValue` for initial state as mentioned above.

**Comment by DamonBlais** [comment]
Related to but not fixed by the steps in: #566

**Comment by felixmosh** [comment]
It is an issue of async, your form get rendered with undefined values once, then the useEffect kicks in, fills the `defaultValue`, bug nothing update formsy about the change.
You can wait till the localStorage is loaded and re-render again.
There are 2 ways that come to mind:
1. Show loading instead of the form.
2. Use `key` on the form that will be related to the async operation.

**Comment by felixmosh** [comment]
@DamonBlais can we close this issue?

**Comment by AlbinoGeek** [comment]
Sorry, that's a GitHub account I don't use often (generally by mistake.)

I'll try and login to close this.

**Comment by DamonBlais** [comment]
This can be closed.

Can't find my 2fa for this
