### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by MilosRasic** [formsy/formsy-react#7]
Once use of deprecated API is removed from the code, this should mostly come down to actually allowing React 16 as dependency.

I'd suggest allowing either v15 or v16 as a peer dependency. Both react and react-dom packages should be covered.

We should test with both React 15 and React 16 to make sure we don't break anything for users who are still stuck with older versions of React.

**Comment by rkuykendall** [comment]
Original issue: https://github.com/christianalfoni/formsy-react/issues/481

**Comment by justinwilson-apollidon** [comment]
Where is this at now? Are we still unable to use formsy-react with React 16? It is causing us to not be able to upgrade from 15 to 16 as we use Formsy for all of our forms.

**Comment by apuntovanini** [comment]
@justinwilson-apollidon see discussion in #11, we might be really close to full support

**Comment by rkuykendall** [comment]
React 16 support was released with version 1.1.0.
