### ISSUE TITLE
Custom isEmail Validator for Specific Domain?

### ISSUE THREAD

**Issue by mjsevilla** [formsy/formsy-react#74]
I'd like to modify, or perhaps, create my own validation rule that is looking for a specific email domain. Example, "sign in with your Gmail account, only." However, with my given code below, I get a `TypeError: Cannot read property 'split' of undefined` error. It appears the validation rule is trying to run on `value` which is undefined when the page loads.

What is the optimal way to validate specific email domains?

    <MyTextInput
      id='email'
      name='Gmail Email'
      validations={{
      gmailValidation: function (values, value) {
        let email = value;
        let split = email.split('@');
        
        if (split[1].toLowerCase() !== 'gmail.com') {
          return 'Please use Gmail';
        } else if (/[~`!#$%\^&*+=\-\[\]\\';,@/{}|\\":<>\?]/g.test(split[[0]])) {
          return 'Please use Gmail';
        } else return true;
      }
      }}
      required
    />

**Comment by MilosRasic** [comment]
I'd say handle the falsy value. if (!value) either return true or false. Generally I'd prefer return true, then add required to the field if it's required. That way you can display different error messages if needed.

**Comment by mjsevilla** [comment]
@MilosRasic , I'm not sure I follow. How does checking `isFalse` help me determine if the email provided is a gmail account?

**Comment by mjsevilla** [comment]
If more clarification is needed, I'd like to create a specific `isEmail` validation rule that only allows one specific email domain.

**Comment by MilosRasic** [comment]
nononono, I'm not saying use another validator, I'm trying to say check if value is false in yours, like this:

```
  validations={{
      gmailValidation: function (values, value) {
        if (!value) {
          return true;
        }

        let email = value;
        let split = email.split('@');
        
        if (split[1].toLowerCase() !== 'gmail.com') {
          return 'Please use Gmail';
        } else if (/[~`!#$%\^&*+=\-\[\]\\';,@/{}|\\":<>\?]/g.test(split[[0]])) {
          return 'Please use Gmail';
        } else return true;
      }
  }}
```

This way validator will not run if value is undefined.

**Comment by mjsevilla** [comment]
Ah, I understand. While that allows the page to load, once I start typing it throws a similar error but on the `split[1].toLowerCase() !== 'gmail.com'` clause. I feel like I might be doing this wrong.
