### ISSUE TITLE
Scroll in IE does not work if form is disabled

### ISSUE THREAD

**Issue by Serhieieva** [formsy/formsy-react#80]
Hi!
In IE scroll inside disabled form does not work. Is it possible to abandon adding disabled prop of Formsy component as an html attribute to form?

The defect can be reproduced by opening fiddle in IE11: https://jsfiddle.net/t0Lphxvo/6/

**Comment by MilosRasic** [comment]
Good catch. Feel free to make a PR. Should be a simple matter of adding disabled to the props spread starting in index.js line 339.
