### ISSUE TITLE
Default required value rule is not complete

### ISSUE THREAD

**Issue by vladoro** [formsy/formsy-react#86]
in file validationRules.js, the rule isDefaultRequiredValue is:
`
  isDefaultRequiredValue(values, value) {
    return value === undefined || value === '';
  },
`
It should be:
`
  isDefaultRequiredValue(values, value) {
    return value === undefined || value === '' || value === null;
  },
`
Because null is not undefined.

**Comment by rkuykendall** [comment]
Yeah, this is something I've encountered a lot, which I admit was very frustrating at first. Currently, I cast all nulls to `''` when starting the form, and then back to `'' => null` on submit. The question is, is there a logical reason to consider `null` a valid required value? Like maybe a radio list with an 'Other' option.

**Comment by rkuykendall** [comment]
Thanks for brining this up though. This seems like a good candidate for a 2.0 change.

**Comment by wa-Nadoo** [comment]
This issue has already been fixed in #82.
