### ISSUE TITLE
onValid fires even when internal validation type shouldn't pass

### ISSUE THREAD

**Issue by andrewlorenz** [formsy/formsy-react#87]
e.g.

```
handleValidForm() {
  console.log("I am valid");
}

render() {
  return (
    <Form onValid={this.handleValidForm}>
      <FormsyText name="email" required type="email" />
    </Form>
  );
}
```

onValid fires on every keypress, regardless of the type="email" validation that was requested.

**Comment by zabute** [comment]
Use the built-in `isEmail` validator:

```jsx
<FormsyText
  name="email"
  required
  type="email"
  validations="isEmail", 
  validationErrors={{
    isEmail: "That's not a valid email"
   }}
/>
```
Also look at [validationErros](https://github.com/formsy/formsy-react/blob/master/API.md#validationErrors) in the api docs.

**Comment by andrewlorenz** [comment]
thanks for the comments zabute, but isValid for the form still fires even if I use isEmail as you suggested. My use case requires me to capture the form's input after standard validation (so I don't have to code my own) but NOT to submit it, at the moment I can't seem to use Formsy like this.

My original issue is all about the fact that isValid is firing when the form data is not at all valid, and Formsy is all about validation(!).
