### ISSUE TITLE
Forked repositories are not searchable

### ISSUE THREAD

**Issue by rkuykendall** [formsy/formsy-react#9]
As much as I want to give due credit to @christianalfoni, it seems like forked repositories are second-class citizens on Github. We should consider making `formsy-react` a normal repository.

<img width="505" alt="screenshot 2017-11-09 16 51 13" src="https://user-images.githubusercontent.com/796717/32631437-43e84030-c56e-11e7-96e7-a11d4df5173d.png">

**Comment by MilosRasic** [comment]
:+1: We can give credit where it's due in the readme.

**Comment by rkuykendall** [comment]
> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support.

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

Well that's pretty awful, but apparently they work relatively fast (~1h).

**Comment by rkuykendall** [comment]
![image](https://user-images.githubusercontent.com/796717/32632848-2b90eeba-c573-11e7-9a98-321d7d37c985.png)

**Comment by rkuykendall** [comment]
Now a real repo! We'll have to add something near the top of the README to give @christianalfoni credit, maybe near where they talk about the original blog post.

![screenshot from 2017-11-11 09-33-30](https://user-images.githubusercontent.com/796717/32690360-886cc608-c6c3-11e7-80ca-62721577e953.png)
