### ISSUE TITLE
Examples to show axios callbacks

### ISSUE THREAD

**Issue by miriam-z** [formsy/formsy-react#92]
I need Formsy component to call Express backend

router.post('/users', function (req, res, next) {
    console.log("Called")
}

Normally in a standard component it would be

<form action="/users" method="POST">

How to connect to backend in Formsy?

**Comment by MilosRasic** [comment]
Formsy form component or a form field wrapped in formsy HOC?

To submit a form, you'll want to use axios in onValidSubmit handler most of the timers.

If you want a form field to make a request when the user does something with it, just use an event handler, same as with any other component.

**Comment by twisty** [comment]
Closing this one. @miriam-z hope you worked this out.
