### ISSUE TITLE
Fate of lib and release directories in v2.0

### ISSUE THREAD

**Issue by MilosRasic** [formsy/formsy-react#96]
Lib directory is where transpiled files are generated when we run the build script, and release contains bundled file and source maps. Currently those files are committed to the repo. Tests also import the transpiled files. So, to break this down into questions:

1) Do we want to to keep committing lib and release to the repo?

Advantages:

-  Users can npm/yarn install directly from github

Disadvantages:

- Every PR is bloated with transpiled and bundled file diffs
- Inconsistency if contributors don't build before making a PR

I'm in favor of adding lib and release to .gitignore. Most projects don't commit their transpiled files and bundles to the repo. We used this as a way to test migration React 16, so the original need is gone. If we need to test changes in the future, we can use a beta release on npm.

2) Do we want to test transpiled files?

Advantages: are there any?

Disadvantages:

- We have to build before testing, or our tests are not going to pick up the latest changes. This makes precommit tests, a nice feature we could have, useless.
- Errors reported by tests are in transpiled code, making them more difficult to debug.

Obviously I'd prefer to test es6 code on precommit. Examples from other projects are more evenly divided here.

3) Do we want to add more build targets? es6 for module key in package.json, etc? I wouldn't mind those but I don't see much value either.

**Comment by rkuykendall** [comment]
With modern Jest testing and a modern build / release system, this is no longer a problem.
